create database CAR_RENTAL;
USE CAR_RENTAL;

CREATE TABLE CUSTOMER(
DL_Number CHAR(8) NOT NULL,
Fname VARCHAR(25) NOT NULL,
Mname VARCHAR(25),
Lname VARCHAR(25) NOT NULL,
Age INT NOT NULL,
Sex CHAR NOT NULL,
Email VARCHAR(30) NOT NULL,
Phone_No INT(10) NOT NULL, 
Pin_Code INT(6) NOT NULL,
Street VARCHAR(25) NOT NULL,
City VARCHAR(20) NOT NULL,
State VARCHAR(20) NOT NULL,
CHECK (Age>=18),
PRIMARY KEY(DL_Number));

CREATE TABLE CAR_DETAILS(
Car_ID VARCHAR(25) NOT NULL,
P_Capacity INT NOT NULL,
L_Capacity INT NOT NULL,
Cost_Per_Day DECIMAL(5,2) NOT NULL,
Late_Fee_Per_Day DECIMAL(5,2) NOT NULL,
Car_Type VARCHAR(15) NOT NULL,
Fuel_Type VARCHAR(15) NOT NULL,
PRIMARY KEY(Car_ID));

CREATE TABLE LOCATION_DETAILS(
Location_ID CHAR(10) NOT NULL,
Pin_Code INT(6) NOT NULL, 
Street VARCHAR(25) NOT NULL, 
City VARCHAR(25) NOT NULL,
State VARCHAR(25) NOT NULL,
PRIMARY KEY (Location_ID));

CREATE TABLE RENTAL_CAR(
Registration_NO CHAR(7) NOT NULL,
Mileage INT NOT NULL,
Model_Year INT(4) NOT NULL,
Distance_Travelled INT NOT NULL,
L_ID CHAR(10) NOT NULL,
C_ID VARCHAR(25) NOT NULL,
PRIMARY KEY (Registration_NO),
FOREIGN KEY (L_ID) REFERENCES LOCATION_DETAILS (Location_ID),
FOREIGN KEY (C_ID) REFERENCES CAR_DETAILS (Car_ID));

CREATE TABLE CAR_INSURANCE(
Insurance_ID CHAR(4) NOT NULL,
Cost DECIMAL(5,2) NOT NULL,
Type VARCHAR(30) NOT NULL,
PRIMARY KEY (Insurance_ID));

CREATE TABLE BOOKING_DETAILS(
Booking_ID CHAR(5) NOT NULL,
Date_From TIMESTAMP NOT NULL,
Date_Till TIMESTAMP NOT NULL,
Amount DECIMAL(10,2) NOT NULL,
Status VARCHAR(10) NOT NULL,
Reg_NO CHAR(7) NOT NULL,
DL_Num CHAR(8) NOT NULL,
Ins_ID CHAR(4) NOT NULL,
PRIMARY KEY (Booking_ID), 
FOREIGN KEY (Reg_NO) REFERENCES RENTAL_CAR (Registration_NO),
FOREIGN KEY (DL_Num) REFERENCES CUSTOMER (DL_Number),
FOREIGN KEY (Ins_ID) REFERENCES CAR_INSURANCE (Insurance_ID));

CREATE TABLE FINAL_BILL(
Bill_ID CHAR(6) NOT NULL,
Bill_Date DATE NOT NULL,
Bill_Status VARCHAR(10) NOT NULL,
Total_Amount Decimal(10,2) NOT NULL,
Tax_Amount DECIMAL(10,2) NOT NULL,
Total_Late_Fee DECIMAL(10,2) NOT NULL,
Discount DECIMAL(10,2) NOT NULL,
B_ID CHAR(5) NOT NULL,
PRIMARY KEY(Bill_ID),
FOREIGN KEY(B_ID) REFERENCES BOOKING_DETAILS(Booking_ID));






